#!/usr/bin/env bash
#
# Bootstrap E2E Test — spec-orch from-zero-to-loop
#
# Simulates a brand-new user experience:
#   1. Clone repo into isolated temp dir
#   2. Create venv + pip install
#   3. spec-orch init --yes  (dynamic project detection)
#   4. spec-orch config check
#   5. spec-orch run-issue   (full pipeline — verification from spec-orch.toml)
#
# NOTHING in this script hardcodes which lint/typecheck/test tools to use.
# All verification commands come from spec-orch.toml generated by `init`.
#
# Usage:
#   ./tests/e2e/bootstrap_test.sh              # dry-run only (no API key)
#   ./tests/e2e/bootstrap_test.sh --full       # full mode (needs MINIMAX_API_KEY)
#
# Exit codes:
#   0 = all checks passed
#   1 = failure

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
FULL_MODE=false
EXIT_CODE=0

for arg in "$@"; do
  case "$arg" in
    --full) FULL_MODE=true ;;
  esac
done

# ---------- helpers ----------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

step() { echo -e "\n${GREEN}▶ STEP: $1${NC}"; }
fail() { echo -e "${RED}✗ FAIL: $1${NC}" >&2; exit 1; }
ok()   { echo -e "${GREEN}✓ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }
info() { echo -e "${CYAN}  $1${NC}"; }

# ---------- pre-flight ----------

step "Pre-flight checks"

command -v python3 &>/dev/null || fail "python3 not found"
ok "python3 found: $(python3 --version)"

command -v git &>/dev/null || fail "git not found"
ok "git found"

if [ "$FULL_MODE" = true ]; then
  [ -n "${MINIMAX_API_KEY:-}" ] || fail "MINIMAX_API_KEY required for --full mode"
  command -v opencode &>/dev/null || fail "opencode CLI not found (required for --full mode)"
  ok "Full mode prerequisites met"
fi

# ---------- Step 1: isolated environment ----------

step "Creating isolated environment"

WORK_DIR=$(mktemp -d -t spec-orch-bootstrap-XXXXXX)
echo "Work directory: $WORK_DIR"

cleanup() {
  echo -e "\n${YELLOW}Cleaning up $WORK_DIR${NC}"
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

git clone --depth 1 "file://$REPO_ROOT" "$WORK_DIR/spec-orch-test" 2>&1 | tail -2
cd "$WORK_DIR/spec-orch-test"
ok "Cloned repo to $WORK_DIR/spec-orch-test"

# ---------- Step 2: venv + install ----------

step "Creating venv and installing spec-orch"

python3 -m venv .venv
source .venv/bin/activate
pip install -e ".[dev]" --quiet 2>&1 | tail -3
ok "Installed spec-orch in isolated venv"

# ---------- Step 3: verify installation ----------

step "Verifying installation"

VERSION=$(spec-orch --version)
echo "spec-orch version: $VERSION"
[ -n "$VERSION" ] || fail "spec-orch --version returned empty"
ok "spec-orch CLI works"

# ---------- Step 4: init (dynamic project detection) ----------

step "Running spec-orch init (dynamic detection)"

rm -f spec-orch.toml

spec-orch init --yes
[ -f spec-orch.toml ] || fail "spec-orch.toml not created by init"
ok "spec-orch.toml generated by dynamic detection"

info "Generated config:"
cat spec-orch.toml
echo ""

# ---------- Step 5: config check ----------

step "Running spec-orch config check"

spec-orch config check || warn "config check had warnings (expected without full setup)"
ok "config check completed"

# ---------- Step 6: run-issue ----------

if [ "$FULL_MODE" != true ]; then
  step "Dry-run: spec-orch run-issue BOOT-E2E (fixture mode)"
  info "Verification commands come from spec-orch.toml (generated by init)"
  info "Builder uses default adapter — may fail without CLI, that's expected"

  set +e
  OUTPUT=$(spec-orch run-issue BOOT-E2E --source fixture 2>&1)
  RUN_EXIT=$?
  set -e

  echo "$OUTPUT"

  if echo "$OUTPUT" | grep -q "issue=BOOT-E2E"; then
    ok "run-issue completed — full pipeline ran"
  elif [ $RUN_EXIT -ne 0 ] && echo "$OUTPUT" | grep -qi "builder\|codex\|adapter\|executable"; then
    ok "run-issue reached builder stage then failed (expected without builder CLI)"
  else
    fail "run-issue produced unexpected output (exit=$RUN_EXIT)"
  fi

  echo ""
  echo -e "${GREEN}═══════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Bootstrap dry-run PASSED                 ${NC}"
  echo -e "${GREEN}  init → config → dynamic verify: OK       ${NC}"
  echo -e "${GREEN}═══════════════════════════════════════════${NC}"
  echo ""
  echo "To run the full pipeline with a real builder:"
  echo "  MINIMAX_API_KEY=\$KEY ./tests/e2e/bootstrap_test.sh --full"
  exit 0
fi

# ---------- Full mode: patch builder ----------

step "Full mode: configuring builder in spec-orch.toml"
info "Only changing [builder] section — verification stays as detected by init"

python3 -c "
import re, sys
content = open('spec-orch.toml').read()
content, n = re.subn(
    r'\[builder\].*?(?=\n\[|\Z)',
    '''[builder]
adapter = \"acpx\"
agent = \"opencode\"
model = \"minimax/MiniMax-M2.5\"
timeout_seconds = 600
''',
    content,
    flags=re.DOTALL,
)
if n == 0:
    sys.exit('Failed to patch [builder] section in spec-orch.toml')
open('spec-orch.toml', 'w').write(content)
"

grep -q 'adapter = "acpx"' spec-orch.toml || fail "Failed to patch spec-orch.toml builder section"
ok "Patched [builder] to ACPX + OpenCode + MiniMax"

info "Final spec-orch.toml:"
cat spec-orch.toml
echo ""

# ---------- Full mode: run ----------

step "Full mode: running spec-orch run-issue BOOT-E2E"
info "Fixture has NO hardcoded verification — all from spec-orch.toml"

set +e
spec-orch run-issue BOOT-E2E --source fixture --live 2>&1
FULL_EXIT=$?
set -e

if [ $FULL_EXIT -ne 0 ]; then
  fail "run-issue failed with exit code $FULL_EXIT"
fi
ok "run-issue completed successfully"

# ---------- Verify results ----------

step "Verifying results"

spec-orch status BOOT-E2E 2>&1 || true
spec-orch explain BOOT-E2E 2>&1 || true

WORKTREE_DIR=".worktrees/BOOT-E2E"
if [ ! -d "$WORKTREE_DIR" ]; then
  fail "Worktree $WORKTREE_DIR not found"
fi

if grep -q "bootstrapped by spec-orch" "$WORKTREE_DIR/pyproject.toml" 2>/dev/null; then
  ok "Builder made the expected change in worktree"
else
  fail "Expected marker not found in worktree pyproject.toml"
fi

echo "Git diff in worktree:"
(cd "$WORKTREE_DIR" && git diff --stat 2>/dev/null) || true

echo ""
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  Bootstrap FULL test PASSED                ${NC}"
echo -e "${GREEN}  checkout → install → init → run: DONE     ${NC}"
echo -e "${GREEN}                                            ${NC}"
echo -e "${GREEN}  All verification driven by spec-orch.toml ${NC}"
echo -e "${GREEN}  (generated by init, not hardcoded)         ${NC}"
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
