"""Synthesize candidate compliance rules from historical failure patterns.

HarnessSynthesizer analyses recent run data (gate failures, verification
failures, deviations) and asks an LLM to propose new compliance rules.
RuleValidator back-tests candidates against historical data and merges
accepted rules into compliance.contracts.yaml.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from spec_orch.services.compliance_engine import load_contracts
from spec_orch.services.evidence_analyzer import EvidenceAnalyzer

if TYPE_CHECKING:
    from spec_orch.domain.context import ContextBundle

logger = logging.getLogger(__name__)

_SYNTHESIZER_SYSTEM_PROMPT = """\
You are a compliance-rule engineer for an AI coding-agent orchestrator.

Given historical failure data and existing compliance contracts, propose NEW
pattern-based compliance rules that would catch the observed failures.

Rules use Python regex patterns applied against builder-event text fields.

Requirements:
- Do NOT duplicate existing contracts.
- Each rule needs at least one regex pattern.
- Patterns must be valid Python regex.
- Prefer precise patterns over overly broad ones.
- severity must be "error" or "warning".
- check_fields should be a subset of ["text"].

Respond with ONLY a JSON array of objects, each with these fields:
  id, name, description, severity, patterns (list[str]), check_fields (list[str])

Example:
[
  {
    "id": "no-sudo-commands",
    "name": "No Sudo Commands",
    "description": "Agents should not run sudo commands.",
    "severity": "error",
    "patterns": ["\\\\bsudo\\\\s+"],
    "check_fields": ["text"]
  }
]

If no new rules are warranted, respond with an empty JSON array: []
"""


@dataclass
class CandidateRule:
    """A candidate compliance rule generated by the synthesizer."""

    id: str
    name: str
    description: str
    severity: str
    patterns: list[str]
    check_fields: list[str]
    source: str = "harness-synthesizer"
    generated_at: str = ""
    source_runs: list[str] = field(default_factory=list)

    def to_contract_dict(self) -> dict[str, Any]:
        """Convert to the dict format used in compliance.contracts.yaml."""
        d: dict[str, Any] = {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "severity": self.severity,
        }
        if self.patterns:
            d["patterns"] = self.patterns
        if self.check_fields:
            d["check_fields"] = self.check_fields
        if self.source:
            d["source"] = self.source
        if self.generated_at:
            d["generated_at"] = self.generated_at
        if self.source_runs:
            d["source_runs"] = self.source_runs
        return d


class HarnessSynthesizer:
    """Generate candidate compliance rules from failure patterns."""

    def __init__(self, repo_root: Path, planner: Any | None = None) -> None:
        self._repo_root = repo_root
        self._planner = planner

    def collect_failure_data(self, last_n: int = 20) -> dict[str, Any]:
        """Collect gate failures, verification failures, and deviations from recent runs."""
        analyzer = EvidenceAnalyzer(self._repo_root)
        run_dirs = analyzer._collect_run_dirs()[-last_n:]

        if not run_dirs:
            return {}

        gate_failures: list[dict[str, Any]] = []
        verification_failures: list[dict[str, Any]] = []
        deviations: list[dict[str, Any]] = []
        run_ids: list[str] = []

        for rd in run_dirs:
            run_id = rd.name
            run_ids.append(run_id)

            report = analyzer._read_report(rd)
            if report is None:
                continue

            failed_conditions = report.get("failed_conditions", [])
            if failed_conditions:
                gate_failures.append(
                    {
                        "run_id": run_id,
                        "failed_conditions": failed_conditions,
                        "mergeable": report.get("mergeable", False),
                    }
                )

            verification = report.get("verification")
            if isinstance(verification, dict):
                for check_name, check_data in verification.items():
                    if isinstance(check_data, dict) and check_data.get("exit_code", 0) != 0:
                        verification_failures.append(
                            {
                                "run_id": run_id,
                                "check": check_name,
                                "command": check_data.get("command", ""),
                                "exit_code": check_data.get("exit_code"),
                            }
                        )

            run_devs = analyzer._read_deviations(rd)
            for dev in run_devs:
                dev["run_id"] = run_id
                deviations.append(dev)

        return {
            "run_ids": run_ids,
            "gate_failures": gate_failures,
            "verification_failures": verification_failures,
            "deviations": deviations,
        }

    def synthesize(
        self,
        last_n: int = 20,
        *,
        context: ContextBundle | None = None,
    ) -> list[CandidateRule]:
        """Generate candidate compliance rules from failure patterns."""
        if self._planner is None:
            return []

        failure_data = self.collect_failure_data(last_n=last_n)
        if not failure_data:
            return []

        contracts_path = self._repo_root / "compliance.contracts.yaml"
        existing = load_contracts(contracts_path)
        existing_summary = [{"id": c.id, "name": c.name, "patterns": c.patterns} for c in existing]

        raw_samples = self._collect_failure_samples(failure_data.get("run_ids", []))
        user_msg = (
            "Here are the existing compliance contracts (do NOT duplicate these):\n"
            f"```json\n{json.dumps(existing_summary, indent=2)}\n```\n\n"
            "Here is the failure data from recent runs:\n"
            f"```json\n{json.dumps(failure_data, indent=2)}\n```\n\n"
        )
        if raw_samples:
            user_msg += (
                "Here are raw builder output samples from failed runs "
                "(use these to craft precise regex patterns):\n"
                f"```\n{raw_samples}\n```\n\n"
            )

        success_samples = self._collect_success_samples(failure_data.get("run_ids", []))
        if success_samples:
            user_msg += (
                "Here are samples from SUCCESSFUL runs (rules must NOT flag these "
                "as violations — use them to avoid false positives):\n"
                f"```\n{success_samples}\n```\n\n"
            )

        context_block = self._render_context(context)
        if context_block:
            user_msg += context_block

        if success_samples:
            user_msg += (
                "Propose new pattern-based compliance rules that would catch these failures. "
                "Ensure each proposed rule does NOT match the success samples above."
            )
        else:
            user_msg += (
                "Propose new pattern-based compliance rules that would catch these failures."
            )

        try:
            response = self._planner.brainstorm(
                conversation_history=[
                    {"role": "system", "content": _SYNTHESIZER_SYSTEM_PROMPT},
                    {"role": "user", "content": user_msg},
                ],
                codebase_context="",
            )
        except Exception:
            logger.exception("LLM call failed during harness synthesis")
            return []

        return self._parse_response(response, failure_data.get("run_ids", []))

    def _collect_failure_samples(self, run_ids: list[str], max_samples: int = 20) -> str:
        """Extract raw builder event text from failed runs for precise pattern crafting."""
        analyzer = EvidenceAnalyzer(self._repo_root)
        run_dirs = analyzer._collect_run_dirs()
        run_id_set = set(run_ids)
        target_dirs = [d for d in run_dirs if d.name in run_id_set]

        samples: list[str] = []
        for rd in target_dirs:
            report = analyzer._read_report(rd)
            if report is None or report.get("mergeable", True):
                continue

            events_path = rd / "telemetry" / "incoming_events.jsonl"
            if not events_path.exists():
                events_path = rd / "builder_events.jsonl"
            if not events_path.exists():
                continue

            try:
                for line in events_path.read_text().splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                        text = obj.get("text") or obj.get("excerpt") or ""
                        if text and len(text) > 10:
                            samples.append(f"[{rd.name}] {text[:300]}")
                            if len(samples) >= max_samples:
                                break
                    except json.JSONDecodeError:
                        continue
            except OSError:
                continue

            if len(samples) >= max_samples:
                break

        return "\n".join(samples)

    def _collect_success_samples(self, run_ids: list[str], max_samples: int = 10) -> str:
        """Extract builder event text from successful runs for false-positive guarding."""
        analyzer = EvidenceAnalyzer(self._repo_root)
        run_dirs = analyzer._collect_run_dirs()
        run_id_set = set(run_ids)
        target_dirs = [d for d in run_dirs if d.name in run_id_set]

        samples: list[str] = []
        for rd in target_dirs:
            report = analyzer._read_report(rd)
            if report is None or not report.get("mergeable", False):
                continue

            events_path = rd / "telemetry" / "incoming_events.jsonl"
            if not events_path.exists():
                events_path = rd / "builder_events.jsonl"
            if not events_path.exists():
                continue

            try:
                for line in events_path.read_text().splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                        text = obj.get("text") or obj.get("excerpt") or ""
                        if text and len(text) > 10:
                            samples.append(f"[{rd.name}/OK] {text[:300]}")
                            if len(samples) >= max_samples:
                                break
                    except json.JSONDecodeError:
                        continue
            except OSError:
                continue

            if len(samples) >= max_samples:
                break

        return "\n".join(samples)

    @staticmethod
    def _render_context(context: ContextBundle | None) -> str:
        """Render ContextBundle fields relevant to harness synthesis."""
        if context is None:
            return ""
        parts: list[str] = []
        if context.learning.similar_failure_samples:
            lines = []
            for s in context.learning.similar_failure_samples[:5]:
                lines.append(f"- {s.get('key', '?')}: {s.get('content', '')[:200]}")
            parts.append(
                "### Historical failure samples (from ContextAssembler)\n" + "\n".join(lines)
            )
        if context.task.constraints:
            parts.append(
                "### Constraints\n" + "\n".join(f"- {c}" for c in context.task.constraints)
            )
        if context.execution.deviation_slices:
            lines = [str(d)[:200] for d in context.execution.deviation_slices[:5]]
            parts.append("### Recent deviations\n" + "\n".join(lines))
        if not parts:
            return ""
        return (
            "\nAdditional context from the orchestration system:\n\n" + "\n\n".join(parts) + "\n\n"
        )

    def _parse_response(self, response: Any, run_ids: list[str]) -> list[CandidateRule]:
        """Parse LLM JSON response into CandidateRule objects."""
        if not isinstance(response, str):
            logger.warning("Non-string LLM response: %s", type(response).__name__)
            return []
        text = response.strip()
        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1:
            logger.warning("Could not find JSON array in LLM response")
            return []

        try:
            items = json.loads(text[start : end + 1])
        except json.JSONDecodeError:
            logger.warning("Failed to parse JSON from LLM response")
            return []

        if not isinstance(items, list):
            return []

        now = datetime.now(UTC).isoformat()
        candidates: list[CandidateRule] = []
        for item in items:
            if not isinstance(item, dict):
                continue
            try:
                candidates.append(
                    CandidateRule(
                        id=item["id"],
                        name=item["name"],
                        description=item.get("description", ""),
                        severity=item.get("severity", "warning"),
                        patterns=item.get("patterns", []),
                        check_fields=item.get("check_fields", ["text"]),
                        generated_at=now,
                        source_runs=run_ids,
                    )
                )
            except (KeyError, TypeError):
                logger.warning("Skipping malformed candidate: %s", item)
        return candidates

    def format_candidates_yaml(self, candidates: list[CandidateRule]) -> str:
        """Format candidates as YAML matching compliance.contracts.yaml format."""
        contracts_list = [c.to_contract_dict() for c in candidates]
        return yaml.dump(
            {"contracts": contracts_list},
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )


class RuleValidator:
    """Back-test and apply candidate compliance rules."""

    def __init__(self, repo_root: Path) -> None:
        self._repo_root = repo_root

    def validate(
        self,
        candidates: list[CandidateRule],
        max_false_positive_rate: float = 0.1,
    ) -> tuple[list[CandidateRule], list[CandidateRule]]:
        """Back-test candidates against historical runs.

        Returns (accepted, rejected) tuple.
        A rule is rejected if:
        - Any pattern fails to compile as valid regex
        - Patterns match too broadly against historical builder events
        """
        accepted: list[CandidateRule] = []
        rejected: list[CandidateRule] = []

        events = self._load_historical_events()
        total_events = len(events)

        for candidate in candidates:
            compiled: list[re.Pattern[str]] = []
            valid = True
            for pattern in candidate.patterns:
                try:
                    if not isinstance(pattern, str):
                        raise TypeError(f"Non-string pattern: {pattern!r}")
                    compiled.append(re.compile(pattern))
                except (re.error, TypeError):
                    logger.warning("Invalid regex in candidate %s: %s", candidate.id, pattern)
                    valid = False
                    break

            if not valid:
                rejected.append(candidate)
                continue

            if not candidate.patterns:
                rejected.append(candidate)
                continue

            if total_events > 0:
                match_count = 0
                for evt_text in events:
                    for pat in compiled:
                        if pat.search(evt_text):
                            match_count += 1
                            break
                false_positive_rate = match_count / total_events
                if false_positive_rate > max_false_positive_rate:
                    logger.info(
                        "Candidate %s rejected: %.1f%% false positive rate (threshold %.1f%%)",
                        candidate.id,
                        false_positive_rate * 100,
                        max_false_positive_rate * 100,
                    )
                    rejected.append(candidate)
                    continue

            accepted.append(candidate)

        return accepted, rejected

    def _load_historical_events(self) -> list[str]:
        """Load text from historical builder events for back-testing."""
        analyzer = EvidenceAnalyzer(self._repo_root)
        run_dirs = analyzer._collect_run_dirs()

        texts: list[str] = []
        for rd in run_dirs:
            events_path = rd / "builder_events.jsonl"
            if not events_path.exists():
                continue
            try:
                for line in events_path.read_text().splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        obj = json.loads(line)
                        text = obj.get("text") or obj.get("excerpt") or ""
                        if text:
                            texts.append(text)
                    except json.JSONDecodeError:
                        continue
            except OSError:
                continue
        return texts

    def apply(
        self,
        accepted: list[CandidateRule],
        contracts_path: Path,
        dry_run: bool = False,
    ) -> str:
        """Merge accepted rules into compliance.contracts.yaml.

        Returns summary string of what was added.
        If dry_run, returns what would change without modifying the file.
        """
        if not accepted:
            return "No rules to apply."

        existing_data: dict[str, Any] = {"contracts": []}
        if contracts_path.exists():
            raw = yaml.safe_load(contracts_path.read_text())
            if isinstance(raw, dict) and isinstance(raw.get("contracts"), list):
                existing_data = raw

        existing_ids = {c["id"] for c in existing_data["contracts"]}
        new_rules: list[dict[str, Any]] = []

        for candidate in accepted:
            if candidate.id in existing_ids:
                logger.info("Skipping duplicate rule: %s", candidate.id)
                continue
            new_rules.append(candidate.to_contract_dict())

        if not new_rules:
            return "All candidate rules already exist in contracts file."

        lines = [f"  - {r['id']}: {r['name']}" for r in new_rules]
        summary = f"Adding {len(new_rules)} rule(s):\n" + "\n".join(lines)

        if dry_run:
            return f"[dry-run] {summary}"

        existing_data["contracts"].extend(new_rules)
        output = yaml.dump(
            existing_data,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

        header = (
            "# Compliance contracts for agent behavior evaluation.\n"
            "# Each contract defines a rule that agent execution traces must satisfy.\n\n"
        )
        contracts_path.write_text(header + output)

        return summary
