"""Knowledge Distiller — unifies scattered Evolver outputs into a single knowledge layer.

Reads from:
  - prompt_history.json (PromptEvolver)
  - scoper_hints.json (PlanStrategyEvolver)
  - compliance.contracts.yaml (HarnessSynthesizer)
  - policies_index.json (PolicyDistiller)
  - evolution_log.jsonl (EvolutionTrigger)
  - EvidenceAnalyzer pattern summary

Writes a structured .spec_orch/knowledge.md that serves as a cross-run
learning notebook — the "MEMORY.md" equivalent for spec-orch.

Inspired by OpenKL's `ok distill` (fact + evidence + confidence)
and mem0's automatic memory extraction.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


class KnowledgeDistiller:
    """Distill Evolver outputs and run history into a unified knowledge file."""

    def __init__(self, repo_root: Path) -> None:
        self._root = repo_root

    def distill(self) -> str:
        """Generate the knowledge markdown from all available sources."""
        sections: list[str] = []
        sections.append(self._header())
        sections.append(self._distill_pattern_summary())
        sections.append(self._distill_prompt_history())
        sections.append(self._distill_scoper_hints())
        sections.append(self._distill_compliance_rules())
        sections.append(self._distill_policies())
        sections.append(self._distill_evolution_log())
        return "\n\n".join(s for s in sections if s)

    def write(self, output_path: Path | None = None) -> Path:
        """Write the distilled knowledge to a file."""
        content = self.distill()
        path = output_path or self._root / ".spec_orch" / "knowledge.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        logger.info("Knowledge distilled to %s (%d chars)", path, len(content))
        return path

    def _header(self) -> str:
        ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        return (
            "# spec-orch Knowledge Base\n\n"
            f"> Auto-generated by KnowledgeDistiller at {ts}.\n"
            "> This file consolidates learning across all evolution cycles.\n"
            "> Do not edit manually — it will be regenerated."
        )

    def _distill_pattern_summary(self) -> str:
        try:
            from spec_orch.services.evidence_analyzer import EvidenceAnalyzer

            analyzer = EvidenceAnalyzer(self._root)
            summary = analyzer.analyze()
            if summary.total_runs == 0:
                return ""
            lines = [
                "## Run History Summary",
                "",
                f"- **Total runs**: {summary.total_runs}",
                f"- **Success rate**: {summary.success_rate:.0%}",
                f"- **Avg verification pass rate**: {summary.average_verification_pass_rate:.0%}",
            ]
            if summary.top_failure_reasons:
                lines.append("\n### Top Failure Reasons\n")
                for reason, count in summary.top_failure_reasons:
                    lines.append(f"- `{reason}` ({count} occurrences)")
            if summary.top_deviation_files:
                lines.append("\n### Most Deviated Files\n")
                for filepath, count in summary.top_deviation_files[:5]:
                    lines.append(f"- `{filepath}` ({count} deviations)")
            return "\n".join(lines)
        except Exception:
            logger.warning("Evidence analysis failed during distillation", exc_info=True)
            return ""

    def _distill_prompt_history(self) -> str:
        path = self._root / "prompt_history.json"
        if not path.exists():
            return ""
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            if not data:
                return ""
            lines = ["## Builder Prompt Variants", ""]
            variants = data if isinstance(data, list) else data.get("variants", [])
            for v in variants[-5:]:
                vid = v.get("variant_id", "unknown")
                success = v.get("success_rate", 0)
                lines.append(f"- **{vid}**: success rate {success:.0%}")
            active = data.get("active_variant") if isinstance(data, dict) else None
            if active:
                lines.append(f"\n*Active variant*: `{active}`")
            return "\n".join(lines)
        except (json.JSONDecodeError, KeyError):
            return ""

    def _distill_scoper_hints(self) -> str:
        path = self._root / "scoper_hints.json"
        if not path.exists():
            return ""
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            hints = data if isinstance(data, list) else data.get("hints", [])
            if not hints:
                return ""
            lines = ["## Scoper Hints (Learned)", ""]
            for hint in hints[-10:]:
                text = hint.get("text", "") if isinstance(hint, dict) else str(hint)
                conf = hint.get("confidence", "?") if isinstance(hint, dict) else "?"
                lines.append(f"- {text} (confidence: {conf})")
            return "\n".join(lines)
        except (json.JSONDecodeError, KeyError):
            return ""

    def _distill_compliance_rules(self) -> str:
        path = self._root / "compliance.contracts.yaml"
        if not path.exists():
            return ""
        try:
            import yaml

            data = yaml.safe_load(path.read_text(encoding="utf-8"))
            if not data:
                return ""
            rules = data.get("rules", data) if isinstance(data, dict) else data
            if not isinstance(rules, list):
                return ""
            lines = ["## Compliance Rules", ""]
            for rule in rules[:15]:
                if isinstance(rule, dict):
                    name = rule.get("name", rule.get("id", "unnamed"))
                    desc = rule.get("description", rule.get("pattern", ""))
                    lines.append(f"- **{name}**: {desc}")
                else:
                    lines.append(f"- {rule}")
            return "\n".join(lines)
        except Exception:
            return ""

    def _distill_policies(self) -> str:
        path = self._root / "policies_index.json"
        if not path.exists():
            path = self._root / "policies" / "policies_index.json"
        if not path.exists():
            return ""
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            policies: list[dict[str, Any]] = (
                data if isinstance(data, list) else data.get("policies", [])
            )
            if not policies:
                return ""
            lines = ["## Distilled Policies", ""]
            for pol in policies[:10]:
                pid = pol.get("policy_id", pol.get("id", "unknown"))
                desc = pol.get("description", pol.get("trigger", ""))
                lines.append(f"- **{pid}**: {desc}")
            return "\n".join(lines)
        except (json.JSONDecodeError, KeyError):
            return ""

    def _distill_evolution_log(self) -> str:
        path = self._root / ".spec_orch_evolution" / "evolution_log.jsonl"
        if not path.exists():
            return ""
        try:
            entries: list[dict[str, Any]] = []
            for line in path.read_text(encoding="utf-8").splitlines():
                if line.strip():
                    entries.append(json.loads(line))
            if not entries:
                return ""
            lines = [
                "## Evolution History",
                "",
                f"- **Total cycles**: {len(entries)}",
            ]
            last = entries[-1]
            lines.append(f"- **Last cycle**: {last.get('timestamp', 'unknown')}")
            evolvers = last.get("evolvers_triggered", [])
            if evolvers:
                lines.append(f"- **Last triggered evolvers**: {', '.join(evolvers)}")
            return "\n".join(lines)
        except (json.JSONDecodeError, KeyError):
            return ""
